name: Skork CI Builder/Test Runner

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Building using Skork.sln
      run: dotnet build Skork.sln --configuration SkorkCI
    - name: Running unit tests using Skork.sln
      run: dotnet test SkorkTests.sln --configuration SkorkCI
